### ISSUE TITLE
revive our imaginary friend

### ISSUE THREAD

**Issue by yomimono** [mirage/canopy-data#22]
Some automation used to take care of automatically posting the IRC logs of our biweekly catchups.  This is less tedious than https://github.com/mirage/canopy-data/issues/16 and it would be great to have it again.  @avsm, @Engil , do you know what is needed to revive our imaginary friend?

**Comment by abbysmal** [comment]
Hi everyone,

The project isn't dead per-se, but I think the major problem was the lack of an automation when pushing logs to git.
Basically the bot was running sporadically, logging inside a local git repository, and then someone needed to push the updates manually.
It seems that nowadays ocaml-git can successfully push to a git repo but I'm not sure how stable it is (@dinosaure ?), and even if we were able to do this in an automated fashion we would get some problems like handling permissions, because I don't believe we want strangers to be able to ask for a git push. (even more so if the end goal is to render it on Canopy).
I'd be willing to give a shot at resurrecting Mirage's IRC logging facility, but I'm not sure what is the best approach at this point.

Have a great day everyone!

**Comment by dinosaure** [comment]
About `ocaml-git`, you can follow mirage/ocaml-git#227 . At this stage, the big deal is to keep the compatibility in the top (API provided) and the bottom (file-system abstraction, unix, mirage). It's lot of plumbing and I work hard about that 👍 !

Then, I will improve the HTTP protocol and provide a `push` request.

**Comment by abbysmal** [comment]
Ok, thank you for your amazing work!
I think it's alright if we just run a cron job to re-push periodically the logs.
If people are still willing to use an IRC bot to store logs on github I can try to give it a shot, however I remember @avsm some months ago who said he had other plans and was working on a solution, is something still happening ?
